name: Cypress Cloud
on: [push]

jobs: 
  cypress-e2e-electron:
   runs-on: ubuntu-latest
   steps: 
     - name: Get code
       uses: actions/checkout@v4.1.4

     - name: Cypress run
       uses: cypress-io/github-action@v6
       with:
          install-command: yarn install
          browser: electron
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
          record: true
          parallel: true # Runs test in parallel using settings above
       env:
          CYPRESS_RECORD_KEY: b6b6116c-5c81-4aab-87e0-7e7836617fe2
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
